name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true

      - name: Installing qemu dependencies
        run: |
          lsb_release -a
          sudo sed -i 's/# deb-src/deb-src/g' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get -y install meson mingw-w64 mingw-w64-tools mingw-w64-i686-dev mingw-w64-x86-64-dev mingw-w64-common
          dpkg -l | grep mingw
          ls -lah /usr/x86_64-w64-mingw32/lib/libpathcch.a

      - name: Building emulator for Windows
        run: tools/build_win.sh
