name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show me apt config
        run: cat /etc/apt/sources.list

      - name: Installing qemu dependencies
        run: sudo apt-get build-dep qemu

      - name: Building emulator for Linux
        run: tools/build.sh

      - name: Building emulator for Windows
        run: tools/build_win.sh
